### ISSUE TITLE
I'm terrible at UX

### ISSUE THREAD

**Issue by chasingSublimity** [chasingSublimity/SwearJar#2]

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/chasingSublimity/SwearJar/2/de69a2bf-daac-4e5e-aa31-05cc5539b89e/0130a4ee-5f69-4587-b413-c47550e2261f) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>
